#include <stdio.h>
#include <string.h>
#include <sysexits.h>
#include <unistd.h>
#include <stddef.h>
#include <stdlib.h>

#include "config.h"
#include "common.h"
#include "vm.h"

static int hadError = 0;

char *REPL_PROMPT = ":>>";

void error(int line, char *message) {
  printf("||line %d | Error %s: %s", line, "", message);
  hadError = 1;
}

int runMain(char *source, char *filename) {
  printf("===Script===\n");
  printf("%s", source);

  VM vim;
  initVM(&vim);

  printf("===Output===\n");
  
  InterpretResult result = interpret(source, filename, &vim);

  if (result == INTERPRET_RUNTIME_ERROR) {
    dumpStacks(&vim);
  }
  freeVM(&vim);
}

int runPrompt() {
  printf("Well, I sure would like to run a REPL, but I just don't know how. \nCan you help me learn? \n");
  VM vim;
  initVM(&vim);
  while (1) {
    printf("%s ", REPL_PROMPT);
    char *line = NULL;
    ssize_t linesize;
    getline(&line, &linesize, stdin); /* This is a GNU extension. Musl users beware! */
    if (!strcmp(line, "exit\n")) {
      printf("Bye bye!\n");
      free(line);
      break;
    }
    printf("%s", line);
    interpret(line, "REPL", &vim);
    hadError = 0;
    free(line); /* Necessary bc of GNU not being Unix */
  }
  freeVM(&vim);
}

static char *readFile(char *filename) {
  FILE *file = fopen(filename, "rb");

  if (file == NULL) {
    fprintf(stderr, "\"%s\" File could not be opened. Figure it out, bucko! \n", filename);
    exit(EX_IOERR);
  }
  
  fseek(file, 0L, SEEK_END);
  size_t filesize = ftell(file);
  rewind(file);

  char *buffer = malloc(filesize + 2);

  if (buffer == NULL) {
    fprintf(stderr, "No memory? 0^o\n\nat least not for files\n");
    exit(EX_IOERR);
  }

  size_t bytesRead = fread(buffer, sizeof(char), filesize, file);
  buffer[bytesRead] = '\n';
  buffer[bytesRead+1] = '\0';

  fclose(file);
  return buffer;
}

static int runFile(char *filename) {
  /* Get da code */
  char *source = readFile(filename);
  /* run da code */
  runMain(source, filename);
  /* free da code *pepe rock* */
  free(source);

  if (hadError) {
    exit(EX_DATAERR);
  }
}

int main(int argc, char **argv) {
  argc--, argv++;

  char *filename = "REPL";

  char *helpstring = "Usage: joint [FILE] [OPTIONS]...\n\nA hand-rolled Trilox interpreter, for when you really need that third option.\n\nOptions:\n -h, --help\t\tPrints this text.\n -f, --file [FILE]\tOpens the file specified.\n --debug [OPTIONS]\tEnables the provided debug options.\n\nDebug Options:\n print-bytecode\t\tPrints the bytecode generated by the compiler before running it.\n log-gc\t\t\tLogs each of the actions taken by the garbage collector, both allocating and freeing memory.\n stress-gc\t\tStress tests the garbage collector by running it everytime memory is allocated.\n";
  
  if (argc == 1) {
    if (strcmp(argv[0], "-h") == 0 || strcmp(argv[0], "--help") == 0) {
      printf("%s", helpstring);
      exit(0);
    } else if (argv[0][0] == '-') {
      fprintf(stderr, "Unknown option: '%s'", argv[0]);
      fprintf(stderr, "\n%s", helpstring);
      exit(EX_USAGE);
    } else {
      filename = argv[0];
      runFile(filename);
    }
  } else {
    
    for (int i = 0; i < argc; i++) {
      if (strcmp(argv[i], "-f") == 0 || strcmp(argv[i], "--file") == 0) {
	i++;
	if (!(i < argc) || argv[i][0] == '-') {
	  fprintf(stderr, "Must include filename after '-f' or '--file' argument!\n");
	  fprintf(stderr, "\n%s", helpstring);
	  exit(EX_USAGE);
	}
	filename = argv[i];
      } else if (strcmp(argv[i], "--debug") == 0) {
	i++;
	while (i < argc) {
	  if (strcmp(argv[i], "print-bytecode") == 0) {
	    DEBUG_PRINT_BYTECODE = 1;
	  } else if (strcmp(argv[i], "log-gc") == 0) {
	    DEBUG_LOG_GC = 1;
	  } else if (strcmp(argv[i], "stress-gc") == 0) {
	    DEBUG_STRESS_GC = 1;
	  } else {
	    if (argv[i][0] == '-') {
	      i--;
	      break;
	    }
	    fprintf(stderr, "Unknown debug option: '%s'", argv[i]);
	    fprintf(stderr, "\n%s", helpstring);
	    exit(EX_USAGE);
	  }
	  i++;
	}
      } else if (strcmp(argv[i], "-p") == 0 || strcmp(argv[i], "--prompt") == 0) {
	i++;
	if (!(i < argc) || argv[i][0] == '-') {
	  fprintf(stderr, "Must include desired REPL prompt after '-p' or '--prompt' argument!\n");
	  fprintf(stderr, "\n%s", helpstring);
	  exit(EX_USAGE);
	}
	REPL_PROMPT = argv[i];
      } else if (i == 0) {
	filename = argv[i];
      } else {
	fprintf(stderr, "Unknown option: '%s'", argv[i]);
	fprintf(stderr, "\n%s", helpstring);
	exit(EX_USAGE);
      }
    }
    
    if (strcmp(filename, "REPL") == 0) {
      runPrompt();
    }
    else {
      runFile(filename);
    }
  }
}
